package com.thoughtworks.lhli.lovelive_rock.model;

import org.json.JSONException;
import org.json.JSONObject;

public class Card {

    private final String id;
    private final String name;
    private final String japaneseName;
    private final JSONObject idol;
    private final String japaneseCollection;
    private final String rarity;
    private final String attribute;
    private final String japaneseAttribute;
    private final boolean isPromo;
    private final String promoItem;
    private final String releaseDate;
    private final boolean japanOnly;
    private final JSONObject event;
    private final boolean isSpecial;
    private final String hp;
    private final String minimumStatisticsSmile;
    private final String minimumStatisticsPure;
    private final String minimumStatisticsCool;
    private final String nonIdolizedMaximumStatisticsSmile;
    private final String nonIdolizedMaximumStatisticsPure;
    private final String nonIdolizedMaximumStatisticsCool;
    private final String idolizedMaximumStatisticsSmile;
    private final String idolizedMaximumStatisticsPure;
    private final String idolizedMaximumStatisticsCool;
    private final String skill;
    private final String japaneseSkill;
    private final String skillDetails;
    private final String japaneseSkillDetails;
    private final String centerSkill;
    private final String japaneseCenterSkill;
    private final String japaneseCenterSkillDetails;
    private final String cardImage;
    private final String cardIdolizedImage;
    private final String roundCardImage;
    private final String videoStory;
    private final String japaneseVideoStory;
    private final String websiteUrl;
    private final String nonIdolizedMaxLevel;
    private final String idolizedMaxLevel;
    private final String ownedCards;

    public Card(JSONObject jsonObject) throws JSONException {
        this.id = jsonObject.getString("id");
        this.name = jsonObject.getString("name");
        this.japaneseName = jsonObject.getString("japanese_name");
        this.idol = jsonObject.getJSONObject("idol");
        this.japaneseCollection = jsonObject.getString("japanese_collection");
        this.rarity = jsonObject.getString("rarity");
        this.attribute = jsonObject.getString("attribute");
        this.japaneseAttribute = jsonObject.getString("japanese_attribute");
        this.isPromo = jsonObject.getBoolean("is_promo");
        this.promoItem = jsonObject.getString("promo_item");
        this.releaseDate = jsonObject.getString("release_date");
        this.japanOnly = jsonObject.getBoolean("japan_only");
        this.event = jsonObject.getJSONObject("event");
        this.isSpecial = jsonObject.getBoolean("is_special");
        this.hp = jsonObject.getString("hp");
        this.minimumStatisticsSmile = jsonObject.getString("minimum_statistics_smile");
        this.minimumStatisticsPure = jsonObject.getString("minimum_statistics_pure");
        this.minimumStatisticsCool = jsonObject.getString("minimum_statistics_cool");
        this.nonIdolizedMaximumStatisticsSmile = jsonObject.getString("non_idolized_maximum_statistics_smile");
        this.nonIdolizedMaximumStatisticsPure = jsonObject.getString("non_idolized_maximum_statistics_pure");
        this.nonIdolizedMaximumStatisticsCool = jsonObject.getString("non_idolized_maximum_statistics_cool");
        this.idolizedMaximumStatisticsSmile = jsonObject.getString("idolized_maximum_statistics_smile");
        this.idolizedMaximumStatisticsPure = jsonObject.getString("idolized_maximum_statistics_pure");
        this.idolizedMaximumStatisticsCool = jsonObject.getString("idolized_maximum_statistics_cool");
        this.skill = jsonObject.getString("skill");
        this.japaneseSkill = jsonObject.getString("japanese_skill");
        this.skillDetails = jsonObject.getString("skill_details");
        this.japaneseSkillDetails = jsonObject.getString("japanese_skill_details");
        this.centerSkill = jsonObject.getString("center_skill");
        this.japaneseCenterSkill = jsonObject.getString("japanese_center_skill");
        this.japaneseCenterSkillDetails = jsonObject.getString("japanese_center_skill_details");
        this.cardImage = jsonObject.getString("card_image");
        this.cardIdolizedImage = jsonObject.getString("card_idolized_image");
        this.roundCardImage = jsonObject.getString("round_card_image");
        this.videoStory = jsonObject.getString("video_story");
        this.japaneseVideoStory = jsonObject.getString("japanese_video_story");
        this.websiteUrl = jsonObject.getString("website_url");
        this.nonIdolizedMaxLevel = jsonObject.getString("non_idolized_max_level");
        this.idolizedMaxLevel = jsonObject.getString("idolized_max_level");
        this.ownedCards = jsonObject.getString("owned_cards");
    }
}
