package com.thoughtworks.lhli.lovelive_rock.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig characterVoiceDaoConfig;
    private final DaoConfig eventDaoConfig;
    private final DaoConfig idolDaoConfig;
    private final DaoConfig cardDaoConfig;
    private final DaoConfig songDaoConfig;

    private final CharacterVoiceDao characterVoiceDao;
    private final EventDao eventDao;
    private final IdolDao idolDao;
    private final CardDao cardDao;
    private final SongDao songDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        characterVoiceDaoConfig = daoConfigMap.get(CharacterVoiceDao.class).clone();
        characterVoiceDaoConfig.initIdentityScope(type);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        idolDaoConfig = daoConfigMap.get(IdolDao.class).clone();
        idolDaoConfig.initIdentityScope(type);

        cardDaoConfig = daoConfigMap.get(CardDao.class).clone();
        cardDaoConfig.initIdentityScope(type);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);

        characterVoiceDao = new CharacterVoiceDao(characterVoiceDaoConfig, this);
        eventDao = new EventDao(eventDaoConfig, this);
        idolDao = new IdolDao(idolDaoConfig, this);
        cardDao = new CardDao(cardDaoConfig, this);
        songDao = new SongDao(songDaoConfig, this);

        registerDao(CharacterVoice.class, characterVoiceDao);
        registerDao(Event.class, eventDao);
        registerDao(Idol.class, idolDao);
        registerDao(Card.class, cardDao);
        registerDao(Song.class, songDao);
    }
    
    public void clear() {
        characterVoiceDaoConfig.getIdentityScope().clear();
        eventDaoConfig.getIdentityScope().clear();
        idolDaoConfig.getIdentityScope().clear();
        cardDaoConfig.getIdentityScope().clear();
        songDaoConfig.getIdentityScope().clear();
    }

    public CharacterVoiceDao getCharacterVoiceDao() {
        return characterVoiceDao;
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public IdolDao getIdolDao() {
        return idolDao;
    }

    public CardDao getCardDao() {
        return cardDao;
    }

    public SongDao getSongDao() {
        return songDao;
    }

}
