package com.thoughtworks.lhli.lovelive_rock.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EVENT".
 */
public class Event implements java.io.Serializable {

    private Long id;
    private String japaneseName;
    private String romajiName;
    private String englishName;
    private String image;
    private String englishImage;
    private String beginning;
    private String end;
    private String englishBeginning;
    private String englishEnd;
    private Boolean japanCurrent;
    private Boolean worldCurrent;
    private String cards;
    private String song;
    private Short japaneseT1Points;
    private Short japaneseT1Rank;
    private Short japaneseT2Points;
    private Short japaneseT2Rank;
    private Short englishT1Points;
    private Short englishT1Rank;
    private Short englishT2Points;
    private Short englishT2Rank;
    private String note;

    public Event() {
    }

    public Event(Long id) {
        this.id = id;
    }

    public Event(Long id, String japaneseName, String romajiName, String englishName, String image, String englishImage, String beginning, String end, String englishBeginning, String englishEnd, Boolean japanCurrent, Boolean worldCurrent, String cards, String song, Short japaneseT1Points, Short japaneseT1Rank, Short japaneseT2Points, Short japaneseT2Rank, Short englishT1Points, Short englishT1Rank, Short englishT2Points, Short englishT2Rank, String note) {
        this.id = id;
        this.japaneseName = japaneseName;
        this.romajiName = romajiName;
        this.englishName = englishName;
        this.image = image;
        this.englishImage = englishImage;
        this.beginning = beginning;
        this.end = end;
        this.englishBeginning = englishBeginning;
        this.englishEnd = englishEnd;
        this.japanCurrent = japanCurrent;
        this.worldCurrent = worldCurrent;
        this.cards = cards;
        this.song = song;
        this.japaneseT1Points = japaneseT1Points;
        this.japaneseT1Rank = japaneseT1Rank;
        this.japaneseT2Points = japaneseT2Points;
        this.japaneseT2Rank = japaneseT2Rank;
        this.englishT1Points = englishT1Points;
        this.englishT1Rank = englishT1Rank;
        this.englishT2Points = englishT2Points;
        this.englishT2Rank = englishT2Rank;
        this.note = note;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getJapaneseName() {
        return japaneseName;
    }

    public void setJapaneseName(String japaneseName) {
        this.japaneseName = japaneseName;
    }

    public String getRomajiName() {
        return romajiName;
    }

    public void setRomajiName(String romajiName) {
        this.romajiName = romajiName;
    }

    public String getEnglishName() {
        return englishName;
    }

    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getEnglishImage() {
        return englishImage;
    }

    public void setEnglishImage(String englishImage) {
        this.englishImage = englishImage;
    }

    public String getBeginning() {
        return beginning;
    }

    public void setBeginning(String beginning) {
        this.beginning = beginning;
    }

    public String getEnd() {
        return end;
    }

    public void setEnd(String end) {
        this.end = end;
    }

    public String getEnglishBeginning() {
        return englishBeginning;
    }

    public void setEnglishBeginning(String englishBeginning) {
        this.englishBeginning = englishBeginning;
    }

    public String getEnglishEnd() {
        return englishEnd;
    }

    public void setEnglishEnd(String englishEnd) {
        this.englishEnd = englishEnd;
    }

    public Boolean getJapanCurrent() {
        return japanCurrent;
    }

    public void setJapanCurrent(Boolean japanCurrent) {
        this.japanCurrent = japanCurrent;
    }

    public Boolean getWorldCurrent() {
        return worldCurrent;
    }

    public void setWorldCurrent(Boolean worldCurrent) {
        this.worldCurrent = worldCurrent;
    }

    public String getCards() {
        return cards;
    }

    public void setCards(String cards) {
        this.cards = cards;
    }

    public String getSong() {
        return song;
    }

    public void setSong(String song) {
        this.song = song;
    }

    public Short getJapaneseT1Points() {
        return japaneseT1Points;
    }

    public void setJapaneseT1Points(Short japaneseT1Points) {
        this.japaneseT1Points = japaneseT1Points;
    }

    public Short getJapaneseT1Rank() {
        return japaneseT1Rank;
    }

    public void setJapaneseT1Rank(Short japaneseT1Rank) {
        this.japaneseT1Rank = japaneseT1Rank;
    }

    public Short getJapaneseT2Points() {
        return japaneseT2Points;
    }

    public void setJapaneseT2Points(Short japaneseT2Points) {
        this.japaneseT2Points = japaneseT2Points;
    }

    public Short getJapaneseT2Rank() {
        return japaneseT2Rank;
    }

    public void setJapaneseT2Rank(Short japaneseT2Rank) {
        this.japaneseT2Rank = japaneseT2Rank;
    }

    public Short getEnglishT1Points() {
        return englishT1Points;
    }

    public void setEnglishT1Points(Short englishT1Points) {
        this.englishT1Points = englishT1Points;
    }

    public Short getEnglishT1Rank() {
        return englishT1Rank;
    }

    public void setEnglishT1Rank(Short englishT1Rank) {
        this.englishT1Rank = englishT1Rank;
    }

    public Short getEnglishT2Points() {
        return englishT2Points;
    }

    public void setEnglishT2Points(Short englishT2Points) {
        this.englishT2Points = englishT2Points;
    }

    public Short getEnglishT2Rank() {
        return englishT2Rank;
    }

    public void setEnglishT2Rank(Short englishT2Rank) {
        this.englishT2Rank = englishT2Rank;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

}
