package com.thoughtworks.lhli.lovelive_rock.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EVENT".
 */
public class Event implements java.io.Serializable {

    private Long id;
    private String japaneseName;
    private String romajiName;
    private String englishName;
    private String image;
    private String englishImage;
    private String beginning;
    private String end;
    private String englishBeginning;
    private String englishEnd;
    private Boolean japanCurrent;
    private Boolean worldCurrent;
    private String song;
    private Long japaneseT1Points;
    private Long japaneseT1Rank;
    private Long japaneseT2Points;
    private Long japaneseT2Rank;
    private Long englishT1Points;
    private Long englishT1Rank;
    private Long englishT2Points;
    private Long englishT2Rank;
    private String note;

    public Event() {
    }

    public Event(Long id) {
        this.id = id;
    }

    public Event(Long id, String japaneseName, String romajiName, String englishName, String image, String englishImage, String beginning, String end, String englishBeginning, String englishEnd, Boolean japanCurrent, Boolean worldCurrent, String song, Long japaneseT1Points, Long japaneseT1Rank, Long japaneseT2Points, Long japaneseT2Rank, Long englishT1Points, Long englishT1Rank, Long englishT2Points, Long englishT2Rank, String note) {
        this.id = id;
        this.japaneseName = japaneseName;
        this.romajiName = romajiName;
        this.englishName = englishName;
        this.image = image;
        this.englishImage = englishImage;
        this.beginning = beginning;
        this.end = end;
        this.englishBeginning = englishBeginning;
        this.englishEnd = englishEnd;
        this.japanCurrent = japanCurrent;
        this.worldCurrent = worldCurrent;
        this.song = song;
        this.japaneseT1Points = japaneseT1Points;
        this.japaneseT1Rank = japaneseT1Rank;
        this.japaneseT2Points = japaneseT2Points;
        this.japaneseT2Rank = japaneseT2Rank;
        this.englishT1Points = englishT1Points;
        this.englishT1Rank = englishT1Rank;
        this.englishT2Points = englishT2Points;
        this.englishT2Rank = englishT2Rank;
        this.note = note;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getJapaneseName() {
        return japaneseName;
    }

    public void setJapaneseName(String japaneseName) {
        this.japaneseName = japaneseName;
    }

    public String getRomajiName() {
        return romajiName;
    }

    public void setRomajiName(String romajiName) {
        this.romajiName = romajiName;
    }

    public String getEnglishName() {
        return englishName;
    }

    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getEnglishImage() {
        return englishImage;
    }

    public void setEnglishImage(String englishImage) {
        this.englishImage = englishImage;
    }

    public String getBeginning() {
        return beginning;
    }

    public void setBeginning(String beginning) {
        this.beginning = beginning;
    }

    public String getEnd() {
        return end;
    }

    public void setEnd(String end) {
        this.end = end;
    }

    public String getEnglishBeginning() {
        return englishBeginning;
    }

    public void setEnglishBeginning(String englishBeginning) {
        this.englishBeginning = englishBeginning;
    }

    public String getEnglishEnd() {
        return englishEnd;
    }

    public void setEnglishEnd(String englishEnd) {
        this.englishEnd = englishEnd;
    }

    public Boolean getJapanCurrent() {
        return japanCurrent;
    }

    public void setJapanCurrent(Boolean japanCurrent) {
        this.japanCurrent = japanCurrent;
    }

    public Boolean getWorldCurrent() {
        return worldCurrent;
    }

    public void setWorldCurrent(Boolean worldCurrent) {
        this.worldCurrent = worldCurrent;
    }

    public String getSong() {
        return song;
    }

    public void setSong(String song) {
        this.song = song;
    }

    public Long getJapaneseT1Points() {
        return japaneseT1Points;
    }

    public void setJapaneseT1Points(Long japaneseT1Points) {
        this.japaneseT1Points = japaneseT1Points;
    }

    public Long getJapaneseT1Rank() {
        return japaneseT1Rank;
    }

    public void setJapaneseT1Rank(Long japaneseT1Rank) {
        this.japaneseT1Rank = japaneseT1Rank;
    }

    public Long getJapaneseT2Points() {
        return japaneseT2Points;
    }

    public void setJapaneseT2Points(Long japaneseT2Points) {
        this.japaneseT2Points = japaneseT2Points;
    }

    public Long getJapaneseT2Rank() {
        return japaneseT2Rank;
    }

    public void setJapaneseT2Rank(Long japaneseT2Rank) {
        this.japaneseT2Rank = japaneseT2Rank;
    }

    public Long getEnglishT1Points() {
        return englishT1Points;
    }

    public void setEnglishT1Points(Long englishT1Points) {
        this.englishT1Points = englishT1Points;
    }

    public Long getEnglishT1Rank() {
        return englishT1Rank;
    }

    public void setEnglishT1Rank(Long englishT1Rank) {
        this.englishT1Rank = englishT1Rank;
    }

    public Long getEnglishT2Points() {
        return englishT2Points;
    }

    public void setEnglishT2Points(Long englishT2Points) {
        this.englishT2Points = englishT2Points;
    }

    public Long getEnglishT2Rank() {
        return englishT2Rank;
    }

    public void setEnglishT2Rank(Long englishT2Rank) {
        this.englishT2Rank = englishT2Rank;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

}
