package com.thoughtworks.lhli.lovelive_rock.data;

import com.thoughtworks.lhli.lovelive_rock.data.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SONG".
 */
public class Song implements java.io.Serializable {

    private Long id;
    private String name;
    private String romajiName;
    private String translatedName;
    private String attribute;
    private Short BPM;
    private Short time;
    private long eventId;
    private Short rank;
    private String dailyRotation;
    private Short dailyRotationPosition;
    private String image;
    private Short easyDifficulty;
    private Short easyNotes;
    private Short normalDifficulty;
    private Short normalNotes;
    private Short hardDifficulty;
    private Short hardNotes;
    private Short expertDifficulty;
    private Short expertRandomDifficulty;
    private Short expertNotes;
    private Boolean available;
    private Long itunesId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SongDao myDao;

    private Event event;
    private Long event__resolvedKey;


    public Song() {
    }

    public Song(Long id) {
        this.id = id;
    }

    public Song(Long id, String name, String romajiName, String translatedName, String attribute, Short BPM, Short time, long eventId, Short rank, String dailyRotation, Short dailyRotationPosition, String image, Short easyDifficulty, Short easyNotes, Short normalDifficulty, Short normalNotes, Short hardDifficulty, Short hardNotes, Short expertDifficulty, Short expertRandomDifficulty, Short expertNotes, Boolean available, Long itunesId) {
        this.id = id;
        this.name = name;
        this.romajiName = romajiName;
        this.translatedName = translatedName;
        this.attribute = attribute;
        this.BPM = BPM;
        this.time = time;
        this.eventId = eventId;
        this.rank = rank;
        this.dailyRotation = dailyRotation;
        this.dailyRotationPosition = dailyRotationPosition;
        this.image = image;
        this.easyDifficulty = easyDifficulty;
        this.easyNotes = easyNotes;
        this.normalDifficulty = normalDifficulty;
        this.normalNotes = normalNotes;
        this.hardDifficulty = hardDifficulty;
        this.hardNotes = hardNotes;
        this.expertDifficulty = expertDifficulty;
        this.expertRandomDifficulty = expertRandomDifficulty;
        this.expertNotes = expertNotes;
        this.available = available;
        this.itunesId = itunesId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSongDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRomajiName() {
        return romajiName;
    }

    public void setRomajiName(String romajiName) {
        this.romajiName = romajiName;
    }

    public String getTranslatedName() {
        return translatedName;
    }

    public void setTranslatedName(String translatedName) {
        this.translatedName = translatedName;
    }

    public String getAttribute() {
        return attribute;
    }

    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    public Short getBPM() {
        return BPM;
    }

    public void setBPM(Short BPM) {
        this.BPM = BPM;
    }

    public Short getTime() {
        return time;
    }

    public void setTime(Short time) {
        this.time = time;
    }

    public long getEventId() {
        return eventId;
    }

    public void setEventId(long eventId) {
        this.eventId = eventId;
    }

    public Short getRank() {
        return rank;
    }

    public void setRank(Short rank) {
        this.rank = rank;
    }

    public String getDailyRotation() {
        return dailyRotation;
    }

    public void setDailyRotation(String dailyRotation) {
        this.dailyRotation = dailyRotation;
    }

    public Short getDailyRotationPosition() {
        return dailyRotationPosition;
    }

    public void setDailyRotationPosition(Short dailyRotationPosition) {
        this.dailyRotationPosition = dailyRotationPosition;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Short getEasyDifficulty() {
        return easyDifficulty;
    }

    public void setEasyDifficulty(Short easyDifficulty) {
        this.easyDifficulty = easyDifficulty;
    }

    public Short getEasyNotes() {
        return easyNotes;
    }

    public void setEasyNotes(Short easyNotes) {
        this.easyNotes = easyNotes;
    }

    public Short getNormalDifficulty() {
        return normalDifficulty;
    }

    public void setNormalDifficulty(Short normalDifficulty) {
        this.normalDifficulty = normalDifficulty;
    }

    public Short getNormalNotes() {
        return normalNotes;
    }

    public void setNormalNotes(Short normalNotes) {
        this.normalNotes = normalNotes;
    }

    public Short getHardDifficulty() {
        return hardDifficulty;
    }

    public void setHardDifficulty(Short hardDifficulty) {
        this.hardDifficulty = hardDifficulty;
    }

    public Short getHardNotes() {
        return hardNotes;
    }

    public void setHardNotes(Short hardNotes) {
        this.hardNotes = hardNotes;
    }

    public Short getExpertDifficulty() {
        return expertDifficulty;
    }

    public void setExpertDifficulty(Short expertDifficulty) {
        this.expertDifficulty = expertDifficulty;
    }

    public Short getExpertRandomDifficulty() {
        return expertRandomDifficulty;
    }

    public void setExpertRandomDifficulty(Short expertRandomDifficulty) {
        this.expertRandomDifficulty = expertRandomDifficulty;
    }

    public Short getExpertNotes() {
        return expertNotes;
    }

    public void setExpertNotes(Short expertNotes) {
        this.expertNotes = expertNotes;
    }

    public Boolean getAvailable() {
        return available;
    }

    public void setAvailable(Boolean available) {
        this.available = available;
    }

    public Long getItunesId() {
        return itunesId;
    }

    public void setItunesId(Long itunesId) {
        this.itunesId = itunesId;
    }

    /** To-one relationship, resolved on first access. */
    public Event getEvent() {
        long __key = this.eventId;
        if (event__resolvedKey == null || !event__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            EventDao targetDao = daoSession.getEventDao();
            Event eventNew = targetDao.load(__key);
            synchronized (this) {
                event = eventNew;
            	event__resolvedKey = __key;
            }
        }
        return event;
    }

    public void setEvent(Event event) {
        if (event == null) {
            throw new DaoException("To-one property 'eventId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.event = event;
            eventId = event.getId();
            event__resolvedKey = eventId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
